# Generated by Django 5.2.1 on 2025-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TslValidityInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_code", models.CharField(max_length=2, verbose_name="Kod państwa")),
                ("country_name", models.CharField(max_length=20, verbose_name="Państwo")),
                ("tsl_operator_name", models.CharField(max_length=255, verbose_name="Nazwa operatora TSL")),
                ("tsl_issue_date", models.DateTimeField(verbose_name="Data wydania TSL")),
                ("tsl_expiry_date", models.DateTimeField(verbose_name="Data ważności TSL")),
                ("tsl_validity_alert", models.CharField(default="", max_length=100, verbose_name="Status TSL")),
            ],
        ),
        migrations.CreateModel(
            name="TspServiceInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_code", models.CharField(max_length=2, verbose_name="Kod państwa")),
                ("country_name", models.CharField(max_length=20, verbose_name="Państwo")),
                ("tsp_name", models.CharField(max_length=255, verbose_name="Dostawca usługi")),
                ("tsp_service_name", models.CharField(max_length=255, verbose_name="Nazwa usługi")),
                ("tsp_service_type", models.CharField(default="", max_length=100, verbose_name="Typ usługi")),
                (
                    "tsp_service_status",
                    models.CharField(
                        choices=[("Granted", "Granted"), ("Withdrawn", "Withdrawn")],
                        max_length=50,
                        verbose_name="Status usługi",
                    ),
                ),
                ("tsp_service_start_date", models.DateTimeField(verbose_name="Start usługi")),
                ("tsp_url", models.CharField(default="", max_length=150, verbose_name="TSP URL")),
                ("crl_url", models.URLField(default="", max_length=150, verbose_name="CRL URL")),
                ("tsp_service_digital_id", models.TextField(default="", verbose_name="ID usługi")),
                (
                    "service_status_app",
                    models.CharField(
                        choices=[
                            ("Nie obsłużona (nowa)", "Nie obsłużona (nowa)"),
                            ("Nie obsłużona (wycofana)", "Nie obsłużona (wycofana)"),
                            ("Obsłużona", "Obsłużona"),
                        ],
                        max_length=100,
                        verbose_name="Status obsługi",
                    ),
                ),
                (
                    "crl_url_status_app",
                    models.CharField(
                        choices=[
                            ("CRL URL ustalony", "CRL URL ustalony"),
                            ("CRL URL nieustalony", "CRL URL nieustalony"),
                        ],
                        max_length=50,
                        verbose_name="Status CRL URL",
                    ),
                ),
            ],
        ),
    ]
