# Generated by Django 5.2.1 on 2025-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TslValidityInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_code", models.CharField(max_length=2, verbose_name="Country Code")),
                ("country_name", models.CharField(max_length=20, verbose_name="Country")),
                ("tsl_operator_name", models.CharField(max_length=255, verbose_name="TSL Operator")),
                ("tsl_issue_date", models.DateTimeField(verbose_name="TSL Issue Date")),
                ("tsl_expiry_date", models.DateTimeField(verbose_name="TSL Expiry Date")),
                ("tsl_validity_alert", models.CharField(default="", max_length=100, verbose_name="TSL Status")),
            ],
        ),
        migrations.CreateModel(
            name="TspServiceInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_code", models.CharField(max_length=2, verbose_name="Country Code")),
                ("country_name", models.CharField(max_length=20, verbose_name="Country")),
                ("tsp_name", models.CharField(max_length=255, verbose_name="Service Provider")),
                ("tsp_service_name", models.CharField(max_length=255, verbose_name="Service Name")),
                ("tsp_service_type", models.CharField(default="", max_length=100, verbose_name="Service Type")),
                (
                    "tsp_service_status",
                    models.CharField(
                        choices=[("Granted", "Granted"), ("Withdrawn", "Withdrawn")],
                        max_length=50,
                        verbose_name="Service Status",
                    ),
                ),
                ("tsp_service_start_date", models.DateTimeField(verbose_name="Service Start Date")),
                ("tsp_url", models.CharField(default="", max_length=150, verbose_name="TSP URL")),
                ("crl_url", models.URLField(default="", max_length=150, verbose_name="CRL URL")),
                ("tsp_service_digital_id", models.TextField(default="", verbose_name="ID")),
                (
                    "service_status_app",
                    models.CharField(
                        choices=[
                            ("Not served (new)", "Not served (new)"),
                            ("Not served (withdrawn)", "Not served (withdrawn)"),
                            ("Served", "Served"),
                        ],
                        max_length=100,
                        verbose_name="Handling Status",
                    ),
                ),
                (
                    "crl_url_status_app",
                    models.CharField(
                        choices=[("CRL URL defined", "CRL URL defined"), ("CRL URL undefined", "CRL URL undefined")],
                        max_length=50,
                        verbose_name="CRL URL Status",
                    ),
                ),
            ],
        ),
    ]
