COUNTRIES_PL = {
    "AT": "Austria",
    "BE": "Belgia",
    "BG": "Bułgaria",
    "HR": "Chorwacja",
    "CY": "Cypr",
    "CZ": "Czechy",
    "DK": "Dania",
    "EE": "Estonia",
    "FI": "Finlandia",
    "FR": "Francja",
    "EL": "Grecja",
    "ES": "Hiszpania",
    "NL": "Holandia",
    "IE": "Irlandia",
    "IS": "Islandia",
    "LI": "Liechtenstein",
    "LT": "Litwa",
    "LU": "Luksemburg",
    "LV": "Łotwa",
    "MT": "Malta",
    "DE": "Niemcy",
    "NO": "Norwegia",
    "PL": "Polska",
    "PT": "Portugalia",
    "RO": "Rumunia",
    "SK": "Słowacja",
    "SI": "Słowenia",
    "CH": "Szwajcaria",
    "SE": "Szwecja",
    "EU": "Unia Europejska",
    "HU": "Węgry",
    "UK": "Wielka Brytania",
    "IT": "Włochy",
}

